
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JSlider;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FindSegmentsDialog3.java
 *
 * Created on 15-Sep-2011, 09:45:30
 */
/**
 *
 * @author jm20
 */
public class FindSegmentsDialog extends javax.swing.JDialog {

    private VCFMeta meta;
    private ArrayList<String> selectedCols;
    private boolean success;
    private int selected;
    private int minMatches;
    private double freqCutoff;
    private String freqFile;
    private ArrayList<Boolean> filterTable;
    private Boolean csq;

    /** Creates new form FindSegmentsDialog3 */
    public FindSegmentsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    FindSegmentsDialog(int s, VCFMeta m, ArrayList<String> oldSelectedCols, Boolean b) {
        meta = m;
        selected = s;
        setMinMatches(selected);
        csq = b;
        initComponents();
        setOldSelectedCols(oldSelectedCols);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        filteringPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minMatchSlider = new javax.swing.JSlider(JSlider.HORIZONTAL,2, selected, selected);
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        freqCutoffField = new javax.swing.JTextField();
        freqFilterBut = new javax.swing.JRadioButton();
        openFreqBut = new javax.swing.JButton();
        freqText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        resultsPanel = new javax.swing.JScrollPane();
        vcfTable = new javax.swing.JTable();
        clearAllBut = new javax.swing.JToggleButton();
        selectAllBut = new javax.swing.JToggleButton();
        CsqPanel = new javax.swing.JPanel();
        csqGeneCB = new javax.swing.JCheckBox();
        csqFeatureCB = new javax.swing.JCheckBox();
        csqCsqCB = new javax.swing.JCheckBox();
        csqAACB = new javax.swing.JCheckBox();
        csqPolyPhenCB = new javax.swing.JCheckBox();
        csqSiftCB = new javax.swing.JCheckBox();
        csqCondelCB = new javax.swing.JCheckBox();
        csqGranthamCB = new javax.swing.JCheckBox();
        csqGerpCB = new javax.swing.JCheckBox();
        csqSelectAllBut = new javax.swing.JButton();
        csqClearAllBut = new javax.swing.JButton();
        cancelBut = new javax.swing.JButton();
        okBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Minimum number of matching chromosomes:");

        minMatchSlider.setMajorTickSpacing(1);
        minMatchSlider.setPaintTicks(true);
        minMatchSlider.setPaintLabels(true);
        minMatchSlider.setSnapToTicks(true);

        jLabel2.setText("Frequency File:");

        jLabel3.setText("Maximum frequency of variants:");

        freqCutoffField.setText("0.05");
        freqCutoffField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freqCutoffFieldActionPerformed(evt);
            }
        });

        freqFilterBut.setText("Filter variants by frequency");

        openFreqBut.setText("Browse");
        openFreqBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFreqButActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout filteringPanelLayout = new org.jdesktop.layout.GroupLayout(filteringPanel);
        filteringPanel.setLayout(filteringPanelLayout);
        filteringPanelLayout.setHorizontalGroup(
            filteringPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(filteringPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(filteringPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(filteringPanelLayout.createSequentialGroup()
                        .add(filteringPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .add(filteringPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, minMatchSlider, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .add(187, 187, 187))
                    .add(filteringPanelLayout.createSequentialGroup()
                        .add(freqFilterBut)
                        .addContainerGap(288, Short.MAX_VALUE))
                    .add(filteringPanelLayout.createSequentialGroup()
                        .add(filteringPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, freqCutoffField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, freqText)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(openFreqBut)
                        .add(295, 295, 295))))
        );
        filteringPanelLayout.setVerticalGroup(
            filteringPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(filteringPanelLayout.createSequentialGroup()
                .add(49, 49, 49)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(minMatchSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(71, 71, 71)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(freqFilterBut)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, Short.MAX_VALUE)
                .add(filteringPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(filteringPanelLayout.createSequentialGroup()
                        .add(jLabel2)
                        .add(36, 36, 36))
                    .add(filteringPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(freqText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(openFreqBut)))
                .add(17, 17, 17)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(freqCutoffField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(107, 107, 107))
        );

        jTabbedPane1.addTab("General Options", filteringPanel);

        vcfTable.setModel(new FilterTableModel(meta));
        resultsPanel.setViewportView(vcfTable);

        clearAllBut.setText("Clear All");
        clearAllBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllButActionPerformed(evt);
            }
        });

        selectAllBut.setText("Select All");
        selectAllBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(112, 112, 112)
                .add(clearAllBut)
                .add(88, 88, 88)
                .add(selectAllBut)
                .addContainerGap(112, Short.MAX_VALUE))
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(resultsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(432, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(clearAllBut)
                    .add(selectAllBut)))
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                    .add(resultsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 424, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(37, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Info Field Options", jPanel1);

        csqGeneCB.setText("Gene - Ensembl stable ID of affected gene");
        csqGeneCB.setEnabled(csq);

        csqFeatureCB.setText("Feature - Ensembl stable ID of feature");
        csqFeatureCB.setEnabled(csq);

        csqCsqCB.setText("Consequence - consequence type of this variation");
        csqCsqCB.setEnabled(csq);
        csqCsqCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csqCsqCBActionPerformed(evt);
            }
        });

        csqAACB.setText("Amino acid change - only given if the variation affects the protein-coding sequence");
        csqAACB.setEnabled(csq);

        csqPolyPhenCB.setText("PolyPhen - the PolyPhen prediction and score");
        csqPolyPhenCB.setEnabled(csq);

        csqSiftCB.setText("SIFT - the SIFT prediction and score");
        csqSiftCB.setEnabled(csq);

        csqCondelCB.setText("Condel - the Condel consensus prediction and score");
        csqCondelCB.setEnabled(csq);

        csqGranthamCB.setText(" Grantham - the Grantham score");
        csqGranthamCB.setEnabled(csq);

        csqGerpCB.setText("GERP - the GERP score");
        csqGerpCB.setEnabled(csq);

        csqSelectAllBut.setText("Select All");
        csqSelectAllBut.setEnabled(csq);
        csqSelectAllBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csqSelectAllButActionPerformed(evt);
            }
        });

        csqClearAllBut.setText("Clear All");
        csqClearAllBut.setEnabled(csq);
        csqClearAllBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csqClearAllButActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout CsqPanelLayout = new org.jdesktop.layout.GroupLayout(CsqPanel);
        CsqPanel.setLayout(CsqPanelLayout);
        CsqPanelLayout.setHorizontalGroup(
            CsqPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CsqPanelLayout.createSequentialGroup()
                .add(36, 36, 36)
                .add(CsqPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(csqPolyPhenCB)
                    .add(csqSiftCB)
                    .add(csqAACB)
                    .add(csqCsqCB)
                    .add(csqFeatureCB)
                    .add(csqGeneCB)
                    .add(csqGranthamCB)
                    .add(CsqPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, CsqPanelLayout.createSequentialGroup()
                            .add(CsqPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(csqClearAllBut)
                                .add(csqGerpCB))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(csqSelectAllBut))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, csqCondelCB)))
                .addContainerGap())
        );
        CsqPanelLayout.setVerticalGroup(
            CsqPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(CsqPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(csqGeneCB)
                .add(18, 18, 18)
                .add(csqFeatureCB)
                .add(18, 18, 18)
                .add(csqCsqCB)
                .add(18, 18, 18)
                .add(csqAACB)
                .add(18, 18, 18)
                .add(csqPolyPhenCB)
                .add(18, 18, 18)
                .add(csqSiftCB)
                .add(18, 18, 18)
                .add(csqCondelCB)
                .add(18, 18, 18)
                .add(csqGranthamCB)
                .add(18, 18, 18)
                .add(csqGerpCB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 64, Short.MAX_VALUE)
                .add(CsqPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(csqClearAllBut)
                    .add(csqSelectAllBut)))
        );

        jTabbedPane1.addTab("Consequence Options", CsqPanel);

        cancelBut.setText("Cancel");
        cancelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButActionPerformed(evt);
            }
        });

        okBut.setText("GO");
        okBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(cancelBut)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 337, Short.MAX_VALUE)
                .add(okBut)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 507, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelBut)
                    .add(okBut))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void freqCutoffFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freqCutoffFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_freqCutoffFieldActionPerformed

private void okButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButActionPerformed
    filterTable = ((FilterTableModel) vcfTable.getModel()).getSelected();
    selectedCols = new ArrayList<String>();
    ArrayList<HashMap<String, String>> infos = meta.getInfo();
    HashMap<String, String> info;
    String id;
    for (int i = 0; i < meta.info.size(); i++) {
        if (filterTable.get(i)) {
            info = infos.get(i);
            id = info.get("ID");
            selectedCols.add(id);
//            selectedInfo.add(meta.getInfo().get(i).get("ID"));
        }
    }

    if (csq) {
        if (this.csqGeneCB.isSelected()) {            
            selectedCols.add("CSQ Gene");
        }
        if (this.csqFeatureCB.isSelected()) {
            selectedCols.add("CSQ Feature");
        }
        if (this.csqCsqCB.isSelected()) {
            selectedCols.add("CSQ Consequence");
        }
        if (this.csqAACB.isSelected()) {
            selectedCols.add("CSQ Amino Acid Change");
        }
        if (this.csqSiftCB.isSelected()) {
            selectedCols.add("CSQ Sift Prediction");
            selectedCols.add("CSQ Sift Score");
        }
        if (this.csqPolyPhenCB.isSelected()) {
            selectedCols.add("CSQ PolyPhen Prediction");
            selectedCols.add("CSQ PolyPhen Score");
        }
        if (this.csqCondelCB.isSelected()) {
            selectedCols.add("CSQ Condel Prediction");
            selectedCols.add("CSQ Condel Score");
        }
        if (this.csqGranthamCB.isSelected()) {
            selectedCols.add("CSQ Grantham Score");
        }
        if (this.csqGerpCB.isSelected()) {
            selectedCols.add("CSQ Gerp Score");
        }
    }

    setFreqFile(freqText.getText());
    setFreqCutoff(Double.parseDouble(freqCutoffField.getText()));
    setMinMatches(minMatchSlider.getValue());
    setSuccess(true);
    this.dispose();
}//GEN-LAST:event_okButActionPerformed

private void cancelButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButActionPerformed
    setSuccess(false);
    this.dispose();
}//GEN-LAST:event_cancelButActionPerformed

private void openFreqButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFreqButActionPerformed
    JFileChooser jfc = new JFileChooser();
    if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        try {
            freqText.setText(jfc.getSelectedFile().getAbsolutePath());
        } finally {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }
}//GEN-LAST:event_openFreqButActionPerformed

private void clearAllButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllButActionPerformed
    int rowCount = ((FilterTableModel) vcfTable.getModel()).getRowCount();
    for (int i = 0; i < rowCount; i++) {
        ((FilterTableModel) vcfTable.getModel()).clearAll(i);
    }
}//GEN-LAST:event_clearAllButActionPerformed

private void selectAllButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllButActionPerformed
    int rowCount = ((FilterTableModel) vcfTable.getModel()).getRowCount();
    for (int i = 0; i < rowCount; i++) {
        ((FilterTableModel) vcfTable.getModel()).selectAll(i);
    }
}//GEN-LAST:event_selectAllButActionPerformed

    private void csqCsqCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csqCsqCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csqCsqCBActionPerformed

    private void csqClearAllButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csqClearAllButActionPerformed

        csqAACB.setSelected(false);
        csqClearAllBut.setSelected(false);
        csqCondelCB.setSelected(false);
        csqCsqCB.setSelected(false);
        csqFeatureCB.setSelected(false);
        csqGeneCB.setSelected(false);
        csqGerpCB.setSelected(false);
        csqGranthamCB.setSelected(false);
        csqPolyPhenCB.setSelected(false);
        csqSiftCB.setSelected(false);
    }

    public JCheckBox getCsqAACB() {
        return csqAACB;
    }

    public JCheckBox getCsqCondelCB() {
        return csqCondelCB;
    }

    public JCheckBox getCsqGranthamCB() {
        return csqGranthamCB;
    }

    public JCheckBox getCsqCsqCB() {
        return csqCsqCB;
    }

    public JCheckBox getCsqFeatureCB() {
        return csqFeatureCB;
    }

    public JCheckBox getCsqGeneCB() {
        return csqGeneCB;
    }

    public JCheckBox getCsqGerpCB() {
        return csqGerpCB;
    }

    public JCheckBox getCsqPolyPhenCB() {
        return csqPolyPhenCB;
    }

    public JCheckBox getCsqSiftCB() {
        return csqSiftCB;
    }//GEN-LAST:event_csqClearAllButActionPerformed

    private void csqSelectAllButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csqSelectAllButActionPerformed

        csqAACB.setSelected(true);
        csqClearAllBut.setSelected(true);
        csqCondelCB.setSelected(true);
        csqCsqCB.setSelected(true);
        csqFeatureCB.setSelected(true);
        csqGeneCB.setSelected(true);
        csqGerpCB.setSelected(true);
        csqGranthamCB.setSelected(true);
        csqPolyPhenCB.setSelected(true);
        csqSiftCB.setSelected(true);
    }//GEN-LAST:event_csqSelectAllButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindSegmentsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindSegmentsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindSegmentsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindSegmentsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FindSegmentsDialog dialog = new FindSegmentsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CsqPanel;
    private javax.swing.JButton cancelBut;
    private javax.swing.JToggleButton clearAllBut;
    private javax.swing.JCheckBox csqAACB;
    private javax.swing.JButton csqClearAllBut;
    private javax.swing.JCheckBox csqCondelCB;
    private javax.swing.JCheckBox csqCsqCB;
    private javax.swing.JCheckBox csqFeatureCB;
    private javax.swing.JCheckBox csqGeneCB;
    private javax.swing.JCheckBox csqGerpCB;
    private javax.swing.JCheckBox csqGranthamCB;
    private javax.swing.JCheckBox csqPolyPhenCB;
    private javax.swing.JButton csqSelectAllBut;
    private javax.swing.JCheckBox csqSiftCB;
    private javax.swing.JPanel filteringPanel;
    private javax.swing.JTextField freqCutoffField;
    private javax.swing.JRadioButton freqFilterBut;
    private javax.swing.JTextField freqText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSlider minMatchSlider;
    private javax.swing.JButton okBut;
    private javax.swing.JButton openFreqBut;
    private javax.swing.JScrollPane resultsPanel;
    private javax.swing.JToggleButton selectAllBut;
    private javax.swing.JTable vcfTable;
    // End of variables declaration//GEN-END:variables

    public ArrayList<String> getSelectedCols() {
        return selectedCols;
    }

    private void setOldSelectedCols(ArrayList<String> oldSelectecCols) {
        if (oldSelectecCols.size() > 0) {
            int rowCount = ((FilterTableModel) vcfTable.getModel()).getRowCount();
            for (String col : oldSelectecCols) {                
                if (col.startsWith("CSQ")) {
                    if (col.matches("CSQ Gene")) {
                        this.csqGeneCB.setSelected(true);
                    }
                    if (col.matches("CSQ Feature")) {                        
                        this.csqFeatureCB.setSelected(true);
                    }
                    if (col.matches("CSQ Consequence")) {                        
                        this.csqCsqCB.setSelected(true);
                    }
                    if (col.matches("CSQ Amino Acid Change")) {                        
                        this.csqAACB.setSelected(true);
                    }
                    if (col.matches("CSQ Sift Prediction") || col.matches("CSQ Sift Score")) {                        
                        this.csqSiftCB.setSelected(true);
                    }
                    if (col.matches("CSQ PolyPhen Prediction") || col.matches("CSQ PolyPhen Score")) {                        
                        this.csqPolyPhenCB.setSelected(true);
                    }
                    if (col.matches("CSQ Condel Prediction") || col.matches("CSQ Condel Score")) {
                        this.csqCondelCB.setSelected(true);
                    }
                    if (col.matches("CSQ Grantham Score")) {                        
                        this.csqGranthamCB.setSelected(true);
                    }
                    if (col.matches("CSQ Gerp Score")) {                        
                        this.csqGerpCB.setSelected(true);
                    }
                } else {                    
                    for (int i = 0; i < rowCount; i++) {                        
                        String id = (String) ((FilterTableModel) vcfTable.getModel()).getValueAt(i, 0);
                        if (id.equals(col)) {
                            ((FilterTableModel) vcfTable.getModel()).setSelected(i, 2);                            
                        }                                               
                    }
                }
            }
        }
    }

    public boolean success() {
        return success;
    }

    private void setSuccess(boolean b) {
        success = b;
    }

    public int getMinMatches() {
        return minMatches;
    }

    private void setMinMatches(int s) {
        minMatches = s;
    }

    public double getFreqCutoff() {
        return freqCutoff;
    }

    private void setFreqCutoff(double d) {
        freqCutoff = d;
    }

    boolean freqFilter() {
        if (freqFilterBut.isSelected()) {
            return true;
        } else {
            return false;
        }
    }

    private void setFreqFile(String s) {
        freqFile = s;
    }

    String getFreqFile() {
        return freqFile;
    }
}
